set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

set(VCPKG_CMAKE_SYSTEM_NAME Darwin)
set(VCPKG_OSX_ARCHITECTURES x86_64)

# 设置最小系统版本
set(VCPKG_OSX_DEPLOYMENT_TARGET "10.15")

# 设置编译器标志
set(VCPKG_CXX_FLAGS "-stdlib=libc++")
set(VCPKG_C_FLAGS "")

# 设置链接器标志
set(VCPKG_LINKER_FLAGS "") 