set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

set(VCPKG_CMAKE_SYSTEM_NAME Windows)

# 设置编译器标志
set(VCPKG_CXX_FLAGS "/EHsc")
set(VCPKG_C_FLAGS "")

# 设置链接器标志
set(VCPKG_LINKER_FLAGS "") 